target_multi: "cyberbullying_type"
target_binary: "cyberbullying_bin"
text: "tweet_text"
text_prepared: "text_prepared"

datasets_path:
    all_data: "./data/all_data.parquet"
    with_user_features: "./data/with_user_features.parquet"
    train: "./data/train.parquet"
    val: "./data/val.parquet"
    test: "./data/test.parquet"
    
    

